//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bunnings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bunnings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.bunnings.com.au/.
        /// </summary>
        internal static string BunningsBaseURL {
            get {
                return ResourceManager.GetString("BunningsBaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string DefaultCountOFSuggestedForYouItems {
            get {
                return ResourceManager.GetString("DefaultCountOFSuggestedForYouItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan and collect Flybuys points in-store on your next project.
        /// </summary>
        internal static string flybuysArticleCaption {
            get {
                return ResourceManager.GetString("flybuysArticleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out more.
        /// </summary>
        internal static string flybuysArticleTitleSearchDialogue {
            get {
                return ResourceManager.GetString("flybuysArticleTitleSearchDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.bunnings.com.au/help-support/flybuys.
        /// </summary>
        internal static string HelpSupportFlyBuysURL {
            get {
                return ResourceManager.GetString("HelpSupportFlyBuysURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested for you.
        /// </summary>
        internal static string LabelSuggestedForYou {
            get {
                return ResourceManager.GetString("LabelSuggestedForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you can get even more out of your projects with Flybuys.
        /// </summary>
        internal static string primaryCustomBannerText {
            get {
                return ResourceManager.GetString("primaryCustomBannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What can we help you find today?.
        /// </summary>
        internal static string SearchDefaultText {
            get {
                return ResourceManager.GetString("SearchDefaultText", resourceCulture);
            }
        }
    }
}
